package com.example.mouvie.model.movie.dto

data class MovieDetailDto(
    val adult: Boolean,
    val backdrop_path: String?,
    val belongs_to_collection: Any?,
    val budget: Int,
    val genres: List<GenreDto>,
    val homepage: String?,
    val id: Int,
    val imdb_id: String?,
    val original_language: String,
    val original_title: String,
    val overview: String?,
    val popularity: Number,
    val poster_path: String?,
    val production_companies: List<CompanyDto>,
    val production_countries: List<CountryDto>,
    val release_date: String,
    val revenue: Int,
    val runtime: Int?,
    val spoken_languages: List<LanguageDto>,
    val status: String,
    val tagline: String?,
    val title: String,
    val video: Boolean,
    val vote_average: Number,
    val vote_count: Int,
)
